library(shiny)
library(igraph)
shinyServer(function(input,output){
  observe({
    inFile<-input$file1
    print(inFile)
    if(is.null(inFile))
      return(NULL)
    dt = read.csv(inFile$datapath, sep=input$sep, quote="'")
    output$newGraph <- suppressWarnings(renderPlot({plotMe(dt,input$nodes)
                                   plot(ng)
                                   output$nodeCount <- renderText({vcount(ng)})
                                   output$edgeCount <- renderText({ecount(ng)})
                                   output$density <- renderText({graph.density(ng)})
                                   ddf <- sort(degree(ng), decreasing = T)
                                   ddf <- as.data.frame(ddf)
                                   names(ddf) <- c('degree rank')                                   
                                   output$degreeList <- renderTable({ddf})
                                   edf <- as.data.frame(get.edgelist(ng))
                                   names(edf) <- c('node A','node B')
                                   output$edgeList <- renderTable({edf})                                                                   
                                   }))
  })
})